import { AppShell } from '@mantine/core'
import Head from 'next/head'
import { ReactNode } from 'react'
import LayoutHeader from './ui/Header'

interface Props {
  children: ReactNode
  meta?: PageMeta
}

export interface PageMeta {
  title: string
}

export default function Layout({ children, meta }: Props) {
  const title = meta?.title ? `${meta.title} - OpenSea` : 'OpenSea'
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/opensea.svg" />
      </Head>

      <AppShell styles={{ main: { padding: 'md' } }} header={<LayoutHeader />}>
        {children}
      </AppShell>
    </>
  )
}
